spring:
  jpa:
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33174/DATA_V1
    username: agd
    password: enter
